version: "3"
services: 
    flask:
        image: flask_clock_with_weather
        build: 
            context: ./flask
            dockerfile: Dockerfile
        container_name: flask_clock_with_weather
        volumes: 
            - ./flask/app:/usr/src/app
        secrets:
            - weather_secrets
        networks: 
            - net_clock_with_weather
        command: /usr/local/bin/gunicorn -w 2 -b 0.0.0.0:8000 app:app --reload
    nginx:
        image: nginx_clock_with_weather
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx_clock_with_weather
        ports: 
            - "8006:80"
        networks: 
            - net_clock_with_weather
secrets:
    weather_secrets:
        file: ./secret.txt
networks: 
    net_clock_with_weather:
        driver: bridge